Este código: Adiciona, link, foto e descrição de Vanessa
reprograma/On5-git-e-github pull request #53
Opened 2020-05-31 15:39 UTC by vaosorio

2020-05-31 18:11 UTC, jmariotto approved these changes

2020-05-31 18:55 UTC, mehljuliao approved these changes
show!

2020-06-06 16:50 UTC, MaichiLydia requested changes

2020-06-06 16:50 UTC, MaichiLydia commented on conteudo/exercicios/7-exercicio-projeto-casa/index.html
> +          <a href="#https://github.com/vaosorio" target="_blank">
Oi Vanessa, tudo bom ?
Aqui foi com o # na frente do link, isso faz com que ele não vá pro seu perfil, adicionei a sugestão aqui:
```suggestion
          <a href="https://github.com/vaosorio" target="_blank">
```

Essa modificação não influencia na sua presença, já marquei como entregue :purple_heart: , é só para seu perfil ficar clicável e direcionar pra sua conta git corretamente

2020-06-07 22:35 UTC, vaosorio commented on conteudo/exercicios/7-exercicio-projeto-casa/index.html
> +          <a href="#https://github.com/vaosorio" target="_blank">
Lydia, aceitei a sugestão de commit, preciso dar o push novamente?

2020-06-08 02:04 UTC, MaichiLydia commented on conteudo/exercicios/7-exercicio-projeto-casa/index.html
> +          <a href="#https://github.com/vaosorio" target="_blank">
Precisa não ! Aprovado aqui, brigadão.

2020-06-08 02:04 UTC, MaichiLydia approved these changes

2020-06-08 02:09 UTC, merged