Adicionando foto e link de Gabriela Turquetti para Github
reprograma/On5-git-e-github pull request #80
Opened 2020-06-03 21:29 UTC by turquetti

2020-06-03 22:55 UTC, mehljuliao approved these changes
👍

2020-06-03 23:00 UTC, Donzellini approved these changes

2020-06-06 17:31 UTC, MaichiLydia approved these changes

2020-06-06 18:05 UTC, MaichiLydia requested changes

2020-06-06 18:05 UTC, MaichiLydia commented on conteudo/exercicios/7-exercicio-projeto-casa/index.html
>            <p>Helena Raíra Magaldi Ribeiro</p>
Oi Gabriela, tudo bom ?

As modificações ficaram corretas, porém foram alteradas na div da Helena, teriam que ficar na linha 79.

Essa modificação não influencia na sua presença, já marquei como entregue :purple_heart: , é só para não gerar conflito e suas informações aparecerem junto com seu nome

Se tiver alguma dúvida ou precisar de ajuda só chamar !

2020-06-08 11:44 UTC, turquetti commented on conteudo/exercicios/7-exercicio-projeto-casa/index.html
>            <p>Helena Raíra Magaldi Ribeiro</p>
Lydia, obrigada pelo feedback! Vou tomar mais cuidado nas próximas vezes!

2020-06-08 23:12 UTC, cecisousa approved these changes

2020-06-09 13:44 UTC, MaichiLydia approved these changes

2020-06-09 13:47 UTC, merged